-- ============================================================================
-- ARDEN - PostgreSQL schema
-- Source: Arden_Logical_ERD_Diagram.drawio (final logical ERD)
-- Target: PostgreSQL 15+ with pgvector
--
-- Design conventions
--   * UUID primary keys are generated by pgcrypto.
--   * All timestamps are stored as timestamptz in UTC.
--   * Flexible lifecycle values use text + CHECK constraints so migrations can
--     evolve them more safely than native PostgreSQL ENUM types.
--   * Cross-table tenant and scope rules are enforced with constraint triggers.
--   * Audit events are append-only.
--   * The vector dimension is intentionally not fixed yet. After selecting the
--     embedding model, change knowledge_chunk.embedding to vector(<dimension>)
--     before adding an HNSW/IVFFlat index.
-- ============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS arden;
SET search_path TO arden, public;

-- --------------------------------------------------------------------------
-- Identity and corporate hierarchy
-- --------------------------------------------------------------------------

CREATE TABLE user_account (
    user_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email           text NOT NULL,
    password_hash   text NOT NULL,
    full_name       text NOT NULL,
    display_name    text,
    status          text NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_account_email UNIQUE (email),
    CONSTRAINT ck_user_account_email_normalized
        CHECK (email = lower(btrim(email)) AND position('@' IN email) > 1),
    CONSTRAINT ck_user_account_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DISABLED'))
);

CREATE TABLE organization (
    organization_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name            text NOT NULL,
    slug            text NOT NULL,
    status          text NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_organization_slug UNIQUE (slug),
    CONSTRAINT ck_organization_slug
        CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_organization_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'ARCHIVED'))
);

CREATE TABLE department (
    department_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    code            text NOT NULL,
    name            text NOT NULL,
    status          text NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_department_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_department_org_code UNIQUE (organization_id, code),
    CONSTRAINT uq_department_id_org UNIQUE (department_id, organization_id),
    CONSTRAINT ck_department_code CHECK (length(btrim(code)) > 0),
    CONSTRAINT ck_department_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE TABLE organization_membership (
    membership_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    user_id         uuid NOT NULL,
    status          text NOT NULL DEFAULT 'ACTIVE',
    joined_at       timestamptz NOT NULL DEFAULT now(),
    left_at         timestamptz,

    CONSTRAINT fk_org_membership_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_org_membership_user
        FOREIGN KEY (user_id)
        REFERENCES user_account (user_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_org_membership_org_user UNIQUE (organization_id, user_id),
    CONSTRAINT uq_membership_id_org UNIQUE (membership_id, organization_id),
    CONSTRAINT ck_org_membership_status
        CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'LEFT')),
    CONSTRAINT ck_org_membership_left_at
        CHECK (left_at IS NULL OR left_at >= joined_at),
    CONSTRAINT ck_org_membership_left_state
        CHECK (
            (status = 'LEFT' AND left_at IS NOT NULL)
            OR (status <> 'LEFT' AND left_at IS NULL)
        )
);

CREATE TABLE department_membership (
    department_membership_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    membership_id            uuid NOT NULL,
    department_id            uuid NOT NULL,
    is_primary               boolean NOT NULL DEFAULT false,
    status                   text NOT NULL DEFAULT 'ACTIVE',
    assigned_at              timestamptz NOT NULL DEFAULT now(),
    removed_at               timestamptz,

    CONSTRAINT fk_dept_membership_membership
        FOREIGN KEY (membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_dept_membership_department
        FOREIGN KEY (department_id)
        REFERENCES department (department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_dept_membership_member_department
        UNIQUE (membership_id, department_id),
    CONSTRAINT ck_dept_membership_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'REMOVED')),
    CONSTRAINT ck_dept_membership_removed_at
        CHECK (removed_at IS NULL OR removed_at >= assigned_at),
    CONSTRAINT ck_dept_membership_removed_state
        CHECK (
            (status = 'REMOVED' AND removed_at IS NOT NULL)
            OR (status <> 'REMOVED' AND removed_at IS NULL)
        )
);

CREATE UNIQUE INDEX uq_dept_membership_one_primary
    ON department_membership (membership_id)
    WHERE is_primary AND status = 'ACTIVE';

-- --------------------------------------------------------------------------
-- Authorization: RBAC + organization/department scope + ABAC policies
-- --------------------------------------------------------------------------

CREATE TABLE role (
    role_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid,
    code            text NOT NULL,
    name            text NOT NULL,
    description     text,
    is_system       boolean NOT NULL DEFAULT false,
    status          text NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_role_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_role_code CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT ck_role_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_role_system_owner
        CHECK (
            (is_system AND organization_id IS NULL)
            OR (NOT is_system AND organization_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_role_system_code
    ON role (code)
    WHERE organization_id IS NULL;

CREATE UNIQUE INDEX uq_role_org_code
    ON role (organization_id, code)
    WHERE organization_id IS NOT NULL;

CREATE TABLE permission (
    permission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    code          text NOT NULL,
    resource_type text NOT NULL,
    action        text NOT NULL,
    description   text,
    status        text NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT uq_permission_code UNIQUE (code),
    CONSTRAINT uq_permission_resource_action UNIQUE (resource_type, action),
    CONSTRAINT ck_permission_code CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT ck_permission_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE role_permission (
    role_id       uuid NOT NULL,
    permission_id uuid NOT NULL,
    granted_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES role (role_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES permission (permission_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE access_scope (
    access_scope_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    department_id   uuid,
    scope_type      text NOT NULL,
    status          text NOT NULL DEFAULT 'ACTIVE',
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_access_scope_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_access_scope_department
        FOREIGN KEY (department_id, organization_id)
        REFERENCES department (department_id, organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_access_scope_id_org
        UNIQUE (access_scope_id, organization_id),
    CONSTRAINT ck_access_scope_type
        CHECK (scope_type IN ('ORGANIZATION', 'DEPARTMENT')),
    CONSTRAINT ck_access_scope_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_access_scope_target
        CHECK (
            (scope_type = 'ORGANIZATION' AND department_id IS NULL)
            OR (scope_type = 'DEPARTMENT' AND department_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_access_scope_organization
    ON access_scope (organization_id)
    WHERE scope_type = 'ORGANIZATION';

CREATE UNIQUE INDEX uq_access_scope_department
    ON access_scope (organization_id, department_id)
    WHERE scope_type = 'DEPARTMENT';

CREATE TABLE role_assignment (
    role_assignment_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    membership_id      uuid NOT NULL,
    role_id            uuid NOT NULL,
    access_scope_id    uuid NOT NULL,
    status             text NOT NULL DEFAULT 'ACTIVE',
    valid_from         timestamptz NOT NULL DEFAULT now(),
    valid_until        timestamptz,
    assigned_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_role_assignment_membership
        FOREIGN KEY (membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_role_assignment_role
        FOREIGN KEY (role_id)
        REFERENCES role (role_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_role_assignment_scope
        FOREIGN KEY (access_scope_id)
        REFERENCES access_scope (access_scope_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_role_assignment_status
        CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    CONSTRAINT ck_role_assignment_validity
        CHECK (valid_until IS NULL OR valid_until > valid_from)
);

CREATE UNIQUE INDEX uq_role_assignment_active
    ON role_assignment (membership_id, role_id, access_scope_id)
    WHERE status = 'ACTIVE';

CREATE TABLE authorization_policy (
    policy_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    permission_id   uuid NOT NULL,
    code            text NOT NULL,
    effect          text NOT NULL,
    condition_json  jsonb,
    version         integer NOT NULL DEFAULT 1,
    status          text NOT NULL DEFAULT 'DRAFT',
    effective_from  timestamptz NOT NULL DEFAULT now(),
    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_authorization_policy_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_authorization_policy_permission
        FOREIGN KEY (permission_id)
        REFERENCES permission (permission_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_authorization_policy_version
        UNIQUE (organization_id, code, version),
    CONSTRAINT ck_authorization_policy_code
        CHECK (code ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT ck_authorization_policy_effect
        CHECK (effect IN ('ALLOW', 'DENY')),
    CONSTRAINT ck_authorization_policy_version CHECK (version > 0),
    CONSTRAINT ck_authorization_policy_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'RETIRED')),
    CONSTRAINT ck_authorization_policy_condition
        CHECK (condition_json IS NULL OR jsonb_typeof(condition_json) = 'object')
);

-- --------------------------------------------------------------------------
-- Private workspace, versioning and HITL publication lifecycle
-- --------------------------------------------------------------------------

CREATE TABLE private_workspace (
    workspace_id  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    membership_id uuid NOT NULL,
    name          text NOT NULL,
    status        text NOT NULL DEFAULT 'ACTIVE',
    created_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_private_workspace_membership
        FOREIGN KEY (membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_private_workspace_membership UNIQUE (membership_id),
    CONSTRAINT ck_private_workspace_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE draft_document (
    draft_id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id       uuid NOT NULL,
    title              text NOT NULL,
    description        text,
    status             text NOT NULL DEFAULT 'ACTIVE',
    current_version_no integer NOT NULL DEFAULT 0,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_draft_document_workspace
        FOREIGN KEY (workspace_id)
        REFERENCES private_workspace (workspace_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_draft_document_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_draft_document_version CHECK (current_version_no >= 0)
);

CREATE TABLE draft_version (
    draft_version_id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    draft_id                 uuid NOT NULL,
    version_no               integer NOT NULL,
    source_uri               text NOT NULL,
    mime_type                text NOT NULL,
    content_hash             text NOT NULL,
    created_by_membership_id uuid NOT NULL,
    created_at               timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_draft_version_draft
        FOREIGN KEY (draft_id)
        REFERENCES draft_document (draft_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_draft_version_creator
        FOREIGN KEY (created_by_membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_draft_version_number UNIQUE (draft_id, version_no),
    CONSTRAINT ck_draft_version_number CHECK (version_no > 0),
    CONSTRAINT ck_draft_version_hash CHECK (length(btrim(content_hash)) > 0)
);

CREATE TABLE shared_submission (
    submission_id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    draft_version_id          uuid NOT NULL,
    submitted_by_membership_id uuid NOT NULL,
    target_scope_type         text NOT NULL,
    target_department_id      uuid,
    status                    text NOT NULL DEFAULT 'PENDING_REVIEW',
    submitted_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_shared_submission_version
        FOREIGN KEY (draft_version_id)
        REFERENCES draft_version (draft_version_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_shared_submission_submitter
        FOREIGN KEY (submitted_by_membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_shared_submission_department
        FOREIGN KEY (target_department_id)
        REFERENCES department (department_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_shared_submission_scope
        CHECK (target_scope_type IN ('ORGANIZATION', 'DEPARTMENT')),
    CONSTRAINT ck_shared_submission_target
        CHECK (
            (target_scope_type = 'ORGANIZATION' AND target_department_id IS NULL)
            OR (target_scope_type = 'DEPARTMENT' AND target_department_id IS NOT NULL)
        ),
    CONSTRAINT ck_shared_submission_status
        CHECK (
            status IN (
                'PENDING_REVIEW', 'APPROVED', 'REJECTED',
                'CHANGES_REQUESTED', 'WITHDRAWN'
            )
        )
);

CREATE TABLE review_decision (
    review_decision_id     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id          uuid NOT NULL,
    reviewer_membership_id uuid NOT NULL,
    decision               text NOT NULL,
    comment                text,
    decided_at             timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_review_decision_submission
        FOREIGN KEY (submission_id)
        REFERENCES shared_submission (submission_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_review_decision_reviewer
        FOREIGN KEY (reviewer_membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_review_decision_value
        CHECK (decision IN ('APPROVED', 'REJECTED', 'CHANGES_REQUESTED'))
);

CREATE TABLE knowledge_base (
    knowledge_base_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id   uuid NOT NULL,
    department_id     uuid,
    name              text NOT NULL,
    scope_type        text NOT NULL,
    status            text NOT NULL DEFAULT 'ACTIVE',
    created_at        timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_knowledge_base_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_base_department
        FOREIGN KEY (department_id, organization_id)
        REFERENCES department (department_id, organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_knowledge_base_id_org
        UNIQUE (knowledge_base_id, organization_id),
    CONSTRAINT ck_knowledge_base_scope
        CHECK (scope_type IN ('ORGANIZATION', 'DEPARTMENT')),
    CONSTRAINT ck_knowledge_base_target
        CHECK (
            (scope_type = 'ORGANIZATION' AND department_id IS NULL)
            OR (scope_type = 'DEPARTMENT' AND department_id IS NOT NULL)
        ),
    CONSTRAINT ck_knowledge_base_status
        CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE UNIQUE INDEX uq_knowledge_base_org_name
    ON knowledge_base (organization_id, lower(name), scope_type)
    WHERE department_id IS NULL;

CREATE UNIQUE INDEX uq_knowledge_base_department_name
    ON knowledge_base (organization_id, department_id, lower(name))
    WHERE department_id IS NOT NULL;

CREATE TABLE published_knowledge_version (
    published_version_id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id             uuid NOT NULL,
    knowledge_base_id         uuid NOT NULL,
    published_by_membership_id uuid NOT NULL,
    title                     text NOT NULL,
    version_no                integer NOT NULL,
    content_uri               text NOT NULL,
    content_hash              text NOT NULL,
    index_status              text NOT NULL DEFAULT 'PENDING',
    published_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_published_version_submission
        FOREIGN KEY (submission_id)
        REFERENCES shared_submission (submission_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_published_version_knowledge_base
        FOREIGN KEY (knowledge_base_id)
        REFERENCES knowledge_base (knowledge_base_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_published_version_publisher
        FOREIGN KEY (published_by_membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_published_version_submission UNIQUE (submission_id),
    CONSTRAINT uq_published_version_number
        UNIQUE (knowledge_base_id, title, version_no),
    CONSTRAINT ck_published_version_number CHECK (version_no > 0),
    CONSTRAINT ck_published_version_hash CHECK (length(btrim(content_hash)) > 0),
    CONSTRAINT ck_published_version_index_status
        CHECK (index_status IN ('PENDING', 'PROCESSING', 'INDEXED', 'FAILED'))
);

-- --------------------------------------------------------------------------
-- Governed RAG data
-- --------------------------------------------------------------------------

CREATE TABLE knowledge_chunk (
    chunk_id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    published_version_id uuid NOT NULL,
    chunk_index          integer NOT NULL,
    content              text NOT NULL,
    section_path         text,
    token_count          integer,
    embedding            vector NOT NULL,
    indexed_at           timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_knowledge_chunk_published_version
        FOREIGN KEY (published_version_id)
        REFERENCES published_knowledge_version (published_version_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_knowledge_chunk_index
        UNIQUE (published_version_id, chunk_index),
    CONSTRAINT ck_knowledge_chunk_index CHECK (chunk_index >= 0),
    CONSTRAINT ck_knowledge_chunk_content CHECK (length(btrim(content)) > 0),
    CONSTRAINT ck_knowledge_chunk_tokens
        CHECK (token_count IS NULL OR token_count > 0)
);

CREATE TABLE user_question (
    question_id  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    membership_id uuid NOT NULL,
    question_text text NOT NULL,
    status        text NOT NULL DEFAULT 'RECEIVED',
    submitted_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_user_question_membership
        FOREIGN KEY (membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_user_question_text CHECK (length(btrim(question_text)) > 0),
    CONSTRAINT ck_user_question_status
        CHECK (
            status IN (
                'RECEIVED', 'PROCESSING', 'ANSWERED',
                'CLARIFICATION_REQUIRED', 'FAILED'
            )
        )
);

CREATE TABLE ai_response (
    response_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id   uuid NOT NULL,
    response_text text NOT NULL,
    status        text NOT NULL DEFAULT 'COMPLETED',
    model_name    text NOT NULL,
    model_version text,
    generated_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_ai_response_question
        FOREIGN KEY (question_id)
        REFERENCES user_question (question_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_ai_response_status
        CHECK (
            status IN (
                'COMPLETED', 'ABSTAINED',
                'CLARIFICATION_REQUIRED', 'FAILED'
            )
        )
);

CREATE TABLE citation (
    citation_id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    response_id   uuid NOT NULL,
    chunk_id      uuid NOT NULL,
    citation_order integer NOT NULL,
    quoted_text   text,
    start_offset  integer,
    end_offset    integer,
    created_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_citation_response
        FOREIGN KEY (response_id)
        REFERENCES ai_response (response_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_citation_chunk
        FOREIGN KEY (chunk_id)
        REFERENCES knowledge_chunk (chunk_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_citation_response_order UNIQUE (response_id, citation_order),
    CONSTRAINT uq_citation_response_chunk UNIQUE (response_id, chunk_id),
    CONSTRAINT ck_citation_order CHECK (citation_order > 0),
    CONSTRAINT ck_citation_offsets
        CHECK (
            (start_offset IS NULL AND end_offset IS NULL)
            OR (
                start_offset IS NOT NULL
                AND end_offset IS NOT NULL
                AND start_offset >= 0
                AND end_offset > start_offset
            )
        )
);

CREATE TABLE audit_event (
    audit_event_id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id      uuid NOT NULL,
    actor_membership_id  uuid,
    role_assignment_id   uuid,
    review_decision_id   uuid,
    question_id          uuid,
    event_type           text NOT NULL,
    outcome              text NOT NULL,
    details_json         jsonb,
    occurred_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_audit_event_organization
        FOREIGN KEY (organization_id)
        REFERENCES organization (organization_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_audit_event_actor
        FOREIGN KEY (actor_membership_id)
        REFERENCES organization_membership (membership_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_audit_event_role_assignment
        FOREIGN KEY (role_assignment_id)
        REFERENCES role_assignment (role_assignment_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_audit_event_review_decision
        FOREIGN KEY (review_decision_id)
        REFERENCES review_decision (review_decision_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_audit_event_question
        FOREIGN KEY (question_id)
        REFERENCES user_question (question_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT ck_audit_event_type CHECK (length(btrim(event_type)) > 0),
    CONSTRAINT ck_audit_event_outcome
        CHECK (outcome IN ('SUCCESS', 'DENIED', 'FAILURE')),
    CONSTRAINT ck_audit_event_details
        CHECK (details_json IS NULL OR jsonb_typeof(details_json) = 'object'),
    CONSTRAINT ck_audit_event_single_subject
        CHECK (
            num_nonnulls(
                role_assignment_id,
                review_decision_id,
                question_id
            ) <= 1
        )
);

-- --------------------------------------------------------------------------
-- Query indexes for foreign keys and common application access paths
-- --------------------------------------------------------------------------

CREATE INDEX ix_department_organization
    ON department (organization_id);
CREATE INDEX ix_org_membership_user
    ON organization_membership (user_id);
CREATE INDEX ix_dept_membership_department
    ON department_membership (department_id, status);
CREATE INDEX ix_role_organization
    ON role (organization_id);
CREATE INDEX ix_role_permission_permission
    ON role_permission (permission_id);
CREATE INDEX ix_role_assignment_member_status
    ON role_assignment (membership_id, status, valid_from, valid_until);
CREATE INDEX ix_role_assignment_scope_status
    ON role_assignment (access_scope_id, status);
CREATE INDEX ix_authorization_policy_lookup
    ON authorization_policy (
        organization_id,
        permission_id,
        status,
        effective_from
    );
CREATE INDEX ix_draft_document_workspace
    ON draft_document (workspace_id, status);
CREATE INDEX ix_draft_version_creator
    ON draft_version (created_by_membership_id);
CREATE INDEX ix_shared_submission_reviewer_queue
    ON shared_submission (target_scope_type, target_department_id, status, submitted_at);
CREATE INDEX ix_shared_submission_submitter
    ON shared_submission (submitted_by_membership_id, submitted_at DESC);
CREATE INDEX ix_review_decision_submission
    ON review_decision (submission_id, decided_at DESC);
CREATE INDEX ix_review_decision_reviewer
    ON review_decision (reviewer_membership_id, decided_at DESC);
CREATE INDEX ix_published_version_kb
    ON published_knowledge_version (knowledge_base_id, published_at DESC);
CREATE INDEX ix_published_version_publisher
    ON published_knowledge_version (published_by_membership_id);
CREATE INDEX ix_question_membership_time
    ON user_question (membership_id, submitted_at DESC);
CREATE INDEX ix_response_question_time
    ON ai_response (question_id, generated_at DESC);
CREATE INDEX ix_citation_chunk
    ON citation (chunk_id);
CREATE INDEX ix_audit_event_org_time
    ON audit_event (organization_id, occurred_at DESC);
CREATE INDEX ix_audit_event_actor_time
    ON audit_event (actor_membership_id, occurred_at DESC)
    WHERE actor_membership_id IS NOT NULL;
CREATE INDEX ix_audit_event_type_time
    ON audit_event (event_type, occurred_at DESC);
CREATE INDEX ix_audit_event_details_gin
    ON audit_event USING gin (details_json)
    WHERE details_json IS NOT NULL;
CREATE INDEX ix_authorization_policy_condition_gin
    ON authorization_policy USING gin (condition_json)
    WHERE condition_json IS NOT NULL;

-- No ANN index is created yet because the embedding dimension/model is not
-- part of the final logical ERD. Once fixed, use for example:
--   ALTER TABLE knowledge_chunk
--     ALTER COLUMN embedding TYPE vector(1536);
--   CREATE INDEX ix_knowledge_chunk_embedding_hnsw
--     ON knowledge_chunk USING hnsw (embedding vector_cosine_ops);

-- --------------------------------------------------------------------------
-- Reusable trigger functions
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_user_account_updated_at
BEFORE UPDATE ON user_account
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_organization_updated_at
BEFORE UPDATE ON organization
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_department_updated_at
BEFORE UPDATE ON department
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_draft_document_updated_at
BEFORE UPDATE ON draft_document
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION reject_row_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION '% is immutable: % is not allowed', TG_TABLE_NAME, TG_OP
        USING ERRCODE = '55000';
END;
$$;

-- Immutable version/snapshot records and append-only governance evidence.
CREATE TRIGGER trg_draft_version_immutable
BEFORE UPDATE OR DELETE ON draft_version
FOR EACH ROW EXECUTE FUNCTION reject_row_mutation();

CREATE TRIGGER trg_review_decision_immutable
BEFORE UPDATE OR DELETE ON review_decision
FOR EACH ROW EXECUTE FUNCTION reject_row_mutation();

CREATE OR REPLACE FUNCTION protect_published_version_content()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'published_knowledge_version is immutable: DELETE is not allowed'
            USING ERRCODE = '55000';
    END IF;

    IF NEW.submission_id IS DISTINCT FROM OLD.submission_id
       OR NEW.knowledge_base_id IS DISTINCT FROM OLD.knowledge_base_id
       OR NEW.published_by_membership_id IS DISTINCT FROM OLD.published_by_membership_id
       OR NEW.title IS DISTINCT FROM OLD.title
       OR NEW.version_no IS DISTINCT FROM OLD.version_no
       OR NEW.content_uri IS DISTINCT FROM OLD.content_uri
       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
       OR NEW.published_at IS DISTINCT FROM OLD.published_at THEN
        RAISE EXCEPTION 'Published content and provenance are immutable; create a new version instead'
            USING ERRCODE = '55000';
    END IF;

    -- index_status is intentionally mutable so the indexing worker can move
    -- PENDING -> PROCESSING -> INDEXED/FAILED without rewriting content.
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_published_version_immutable
BEFORE UPDATE OR DELETE ON published_knowledge_version
FOR EACH ROW EXECUTE FUNCTION protect_published_version_content();

CREATE TRIGGER trg_audit_event_append_only
BEFORE UPDATE OR DELETE ON audit_event
FOR EACH ROW EXECUTE FUNCTION reject_row_mutation();

-- --------------------------------------------------------------------------
-- Cross-table tenant and governance rules
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION validate_department_membership()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    membership_org uuid;
    department_org uuid;
BEGIN
    SELECT organization_id
      INTO STRICT membership_org
      FROM organization_membership
     WHERE membership_id = NEW.membership_id;

    SELECT organization_id
      INTO STRICT department_org
      FROM department
     WHERE department_id = NEW.department_id;

    IF membership_org <> department_org THEN
        RAISE EXCEPTION 'Membership and department must belong to the same organization'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_department_membership
AFTER INSERT OR UPDATE OF membership_id, department_id
ON department_membership
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_department_membership();

CREATE OR REPLACE FUNCTION validate_role_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    membership_org uuid;
    scope_org      uuid;
    role_org       uuid;
BEGIN
    SELECT organization_id
      INTO STRICT membership_org
      FROM organization_membership
     WHERE membership_id = NEW.membership_id;

    SELECT organization_id
      INTO STRICT scope_org
      FROM access_scope
     WHERE access_scope_id = NEW.access_scope_id;

    SELECT organization_id
      INTO role_org
      FROM role
     WHERE role_id = NEW.role_id;

    IF membership_org <> scope_org THEN
        RAISE EXCEPTION 'Membership and access scope must belong to the same organization'
            USING ERRCODE = '23514';
    END IF;

    IF role_org IS NOT NULL AND role_org <> membership_org THEN
        RAISE EXCEPTION 'Organization-specific role cannot be assigned across tenants'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_role_assignment
AFTER INSERT OR UPDATE OF membership_id, role_id, access_scope_id
ON role_assignment
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_role_assignment();

CREATE OR REPLACE FUNCTION validate_draft_version_creator()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    owner_membership uuid;
    owner_org        uuid;
    creator_org      uuid;
BEGIN
    SELECT w.membership_id, m.organization_id
      INTO STRICT owner_membership, owner_org
      FROM draft_document d
      JOIN private_workspace w ON w.workspace_id = d.workspace_id
      JOIN organization_membership m ON m.membership_id = w.membership_id
     WHERE d.draft_id = NEW.draft_id;

    SELECT organization_id
      INTO STRICT creator_org
      FROM organization_membership
     WHERE membership_id = NEW.created_by_membership_id;

    IF owner_org <> creator_org THEN
        RAISE EXCEPTION 'Draft version creator cannot cross organization boundaries'
            USING ERRCODE = '23514';
    END IF;

    -- Authorization for a non-owner creator remains an application-level RBAC
    -- decision; this trigger only guarantees tenant isolation.
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_draft_version_creator
AFTER INSERT ON draft_version
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_draft_version_creator();

CREATE OR REPLACE FUNCTION advance_draft_current_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE draft_document
       SET current_version_no = GREATEST(current_version_no, NEW.version_no)
     WHERE draft_id = NEW.draft_id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_advance_draft_current_version
AFTER INSERT ON draft_version
FOR EACH ROW EXECUTE FUNCTION advance_draft_current_version();

CREATE OR REPLACE FUNCTION validate_shared_submission()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    draft_org      uuid;
    submitter_org  uuid;
    department_org uuid;
BEGIN
    SELECT owner_membership.organization_id
      INTO STRICT draft_org
      FROM draft_version v
      JOIN draft_document d ON d.draft_id = v.draft_id
      JOIN private_workspace w ON w.workspace_id = d.workspace_id
      JOIN organization_membership owner_membership
        ON owner_membership.membership_id = w.membership_id
     WHERE v.draft_version_id = NEW.draft_version_id;

    SELECT organization_id
      INTO STRICT submitter_org
      FROM organization_membership
     WHERE membership_id = NEW.submitted_by_membership_id;

    IF draft_org <> submitter_org THEN
        RAISE EXCEPTION 'Submission cannot cross organization boundaries'
            USING ERRCODE = '23514';
    END IF;

    IF NEW.target_department_id IS NOT NULL THEN
        SELECT organization_id
          INTO STRICT department_org
          FROM department
         WHERE department_id = NEW.target_department_id;

        IF department_org <> submitter_org THEN
            RAISE EXCEPTION 'Target department must belong to the submitter organization'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_shared_submission
AFTER INSERT OR UPDATE OF draft_version_id,
                          submitted_by_membership_id,
                          target_scope_type,
                          target_department_id
ON shared_submission
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_shared_submission();

CREATE OR REPLACE FUNCTION validate_review_decision()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    submitter_id  uuid;
    submitter_org uuid;
    reviewer_org  uuid;
BEGIN
    SELECT s.submitted_by_membership_id, m.organization_id
      INTO STRICT submitter_id, submitter_org
      FROM shared_submission s
      JOIN organization_membership m
        ON m.membership_id = s.submitted_by_membership_id
     WHERE s.submission_id = NEW.submission_id;

    SELECT organization_id
      INTO STRICT reviewer_org
      FROM organization_membership
     WHERE membership_id = NEW.reviewer_membership_id;

    IF NEW.reviewer_membership_id = submitter_id THEN
        RAISE EXCEPTION 'Reviewer cannot approve or reject their own submission'
            USING ERRCODE = '23514';
    END IF;

    IF reviewer_org <> submitter_org THEN
        RAISE EXCEPTION 'Reviewer and submission must belong to the same organization'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_review_decision
AFTER INSERT ON review_decision
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_review_decision();

CREATE OR REPLACE FUNCTION apply_review_decision()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE shared_submission
       SET status = NEW.decision
     WHERE submission_id = NEW.submission_id;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_apply_review_decision
AFTER INSERT ON review_decision
FOR EACH ROW EXECUTE FUNCTION apply_review_decision();

CREATE OR REPLACE FUNCTION validate_published_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    submission_status text;
    submission_org    uuid;
    knowledge_org     uuid;
    publisher_org     uuid;
BEGIN
    SELECT s.status, m.organization_id
      INTO STRICT submission_status, submission_org
      FROM shared_submission s
      JOIN organization_membership m
        ON m.membership_id = s.submitted_by_membership_id
     WHERE s.submission_id = NEW.submission_id;

    SELECT organization_id
      INTO STRICT knowledge_org
      FROM knowledge_base
     WHERE knowledge_base_id = NEW.knowledge_base_id;

    SELECT organization_id
      INTO STRICT publisher_org
      FROM organization_membership
     WHERE membership_id = NEW.published_by_membership_id;

    IF submission_status <> 'APPROVED' THEN
        RAISE EXCEPTION 'Only an APPROVED submission can be published'
            USING ERRCODE = '23514';
    END IF;

    IF submission_org <> knowledge_org OR submission_org <> publisher_org THEN
        RAISE EXCEPTION 'Submission, knowledge base and publisher must share one organization'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_published_version
AFTER INSERT ON published_knowledge_version
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_published_version();

CREATE OR REPLACE FUNCTION validate_citation_tenant_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    question_membership uuid;
    question_org        uuid;
    knowledge_org       uuid;
    knowledge_scope     text;
    knowledge_department uuid;
    has_department_access boolean;
BEGIN
    SELECT q.membership_id, m.organization_id
      INTO STRICT question_membership, question_org
      FROM ai_response r
      JOIN user_question q ON q.question_id = r.question_id
      JOIN organization_membership m ON m.membership_id = q.membership_id
     WHERE r.response_id = NEW.response_id;

    SELECT kb.organization_id, kb.scope_type, kb.department_id
      INTO STRICT knowledge_org, knowledge_scope, knowledge_department
      FROM knowledge_chunk c
      JOIN published_knowledge_version pv
        ON pv.published_version_id = c.published_version_id
      JOIN knowledge_base kb
        ON kb.knowledge_base_id = pv.knowledge_base_id
     WHERE c.chunk_id = NEW.chunk_id;

    IF question_org <> knowledge_org THEN
        RAISE EXCEPTION 'Citation cannot expose knowledge from another organization'
            USING ERRCODE = '23514';
    END IF;

    IF knowledge_scope = 'DEPARTMENT' THEN
        SELECT EXISTS (
            SELECT 1
              FROM department_membership dm
             WHERE dm.membership_id = question_membership
               AND dm.department_id = knowledge_department
               AND dm.status = 'ACTIVE'
        ) INTO has_department_access;

        IF NOT has_department_access THEN
            RAISE EXCEPTION 'Question membership cannot cite an inaccessible department chunk'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_citation_tenant_scope
AFTER INSERT OR UPDATE OF response_id, chunk_id
ON citation
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_citation_tenant_scope();

CREATE OR REPLACE FUNCTION validate_audit_event_tenant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    related_org uuid;
BEGIN
    IF NEW.actor_membership_id IS NOT NULL THEN
        SELECT organization_id
          INTO STRICT related_org
          FROM organization_membership
         WHERE membership_id = NEW.actor_membership_id;

        IF related_org <> NEW.organization_id THEN
            RAISE EXCEPTION 'Audit actor must belong to the audit organization'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.role_assignment_id IS NOT NULL THEN
        SELECT m.organization_id
          INTO STRICT related_org
          FROM role_assignment ra
          JOIN organization_membership m ON m.membership_id = ra.membership_id
         WHERE ra.role_assignment_id = NEW.role_assignment_id;

        IF related_org <> NEW.organization_id THEN
            RAISE EXCEPTION 'Audited role assignment belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.review_decision_id IS NOT NULL THEN
        SELECT m.organization_id
          INTO STRICT related_org
          FROM review_decision rd
          JOIN shared_submission s ON s.submission_id = rd.submission_id
          JOIN organization_membership m
            ON m.membership_id = s.submitted_by_membership_id
         WHERE rd.review_decision_id = NEW.review_decision_id;

        IF related_org <> NEW.organization_id THEN
            RAISE EXCEPTION 'Audited review decision belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.question_id IS NOT NULL THEN
        SELECT m.organization_id
          INTO STRICT related_org
          FROM user_question q
          JOIN organization_membership m ON m.membership_id = q.membership_id
         WHERE q.question_id = NEW.question_id;

        IF related_org <> NEW.organization_id THEN
            RAISE EXCEPTION 'Audited question belongs to another organization'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_validate_audit_event_tenant
AFTER INSERT ON audit_event
DEFERRABLE INITIALLY IMMEDIATE
FOR EACH ROW EXECUTE FUNCTION validate_audit_event_tenant();

-- --------------------------------------------------------------------------
-- Documentation embedded in the database
-- --------------------------------------------------------------------------

COMMENT ON SCHEMA arden IS
    'Arden governed multi-tenant knowledge and secure RAG domain';
COMMENT ON TABLE organization_membership IS
    'Association between one user identity and one tenant organization';
COMMENT ON TABLE department_membership IS
    'Department participation of an organization membership';
COMMENT ON TABLE role_assignment IS
    'Role granted to an organization membership within an access scope';
COMMENT ON TABLE draft_version IS
    'Immutable snapshot of a private draft document';
COMMENT ON TABLE review_decision IS
    'Immutable Human-in-the-Loop decision for a shared submission';
COMMENT ON TABLE published_knowledge_version IS
    'Immutable approved knowledge version attached to one knowledge base';
COMMENT ON TABLE knowledge_chunk IS
    'Retrievable RAG chunk derived from an immutable published version';
COMMENT ON COLUMN knowledge_chunk.embedding IS
    'pgvector embedding; dimension must be fixed when the embedding model is selected';
COMMENT ON TABLE citation IS
    'Evidence link from an AI response to an authorized knowledge chunk';
COMMENT ON TABLE audit_event IS
    'Append-only governance and authorization evidence';

COMMIT;

